FreeLibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from FreeLibrary import settings
from books import views as books_views
from account import views as account_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('', books_views.index, name='index'),
    path('account/', include('account.urls')),

    path('signup/', account_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',redirect_field_name='next',redirect_authenticated_user=True),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path, include

from . import views


app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_book', views.add_book, name='addbook'),
    path('book/<int:book_id>', views.detail_book, name='detail'),
    path('<int:book_id>/recommend',views.recommend_book,name="recommend"),
    path('search',views.search,name="search"),
    path('category/<category>',views.category,name="category"),
    path('author/<author>',views.author,name="author"),
    path('download/<book>/',views.download_book,name="download"),




]

books/models.py
import os
from datetime import timezone, datetime

from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Gender(models.Model):
    name = models.CharField('Nombre', max_length=50)

    categories = models.Manager()

    class Meta:
        verbose_name = "Genero"
        verbose_name_plural = "Generos"

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField('Nombre', max_length=50)

    authors = models.Manager()

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField('Nombre', max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Autor')
    description = models.TextField('Descripcion', null=False)
    gender = models.ManyToManyField(Gender)
    amount_pages = models.IntegerField('Cantidad de paginas')
    amount_chapter = models.IntegerField('Cantidad de capitulos')
    pub_date = models.DateTimeField(auto_now_add=True)
    recommended = models.IntegerField('Veces Recomendado', default=0)
    # content_adult = models.BooleanField('Solo para adultos?', default=1)
    public = models.BooleanField('Publico', default=0)
    file_book = models.FileField(verbose_name='Libro', upload_to='', default="")
    img_book = models.ImageField(verbose_name='Foto Portada', upload_to='', default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="")

    books = models.Manager()  # The default manager.

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libros"


class Comment(models.Model):
    text = models.TextField(verbose_name='Comentario', null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, default="")
    datetime = models.DateTimeField(auto_now_add=True)


    comments = models.Manager()

    def get_comment_book(book_id):
        return models.Manager().filter(book_id=book_id)

    def __str__(self):
        return self.text
"""
class Download(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="")
    datetime = models.DateTimeField(auto_now_add=True)


"""

books/forms.py
from django import forms
from django.forms import ModelForm, Textarea, Select, SelectMultiple, CheckboxInput, FileInput
from django.forms.widgets import Input
from easy_select2 import select2_modelform_meta, select2_modelform

from books.models import Book


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book

        fields = (
            'name', 'description', 'author', 'gender', 'amount_pages', 'amount_chapter',
            'img_book', 'file_book')

        labels = {
            'name': ('Nombre'),
        }

        widgets = {
            'name': Input(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'author': Select(attrs={'class': 'form-control', 'placeholder': 'Autor'}),
            'gender': SelectMultiple(attrs={'class': 'form-control'}),
            'amount_pages': Input(attrs={'class': 'form-control'}),
            'amount_chapter': Input(attrs={'class': 'form-control'}),
            'content_adult': Input(attrs={'class': 'form-control'}),
            'img_book': FileInput(attrs={'class': 'form-control'}),
            'file_book': FileInput(attrs={'class': 'form-control'}),
        }

books/views.py
import os


from django.core.paginator import Paginator
from django.db.models.functions import Coalesce, Lower
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404, redirect

from FreeLibrary import settings
from books.forms import AddBookForm
from .models import Book, Gender, Comment, Author


def index(request):
    book_list = Book.books.order_by(Lower('pub_date').desc()).filter(public=True)
    paginator = Paginator(book_list, 8)  # Show 8 book per page

    page = request.GET.get('page')
    books = paginator.get_page(page)
    context = {
        'books': books,
        'categories': Gender.categories.all(),
        'authors': Author.authors.all(),

    }

    return render(request, 'books/index.html', context)


@login_required
def add_book(request):
    if request.method == "POST":
        form = AddBookForm(request.POST, request.FILES)
        if form.is_valid():
            blog_item = form.save(commit=False)
            blog_item.user = request.user
            blog_item.save()

            return redirect('books:index')

    else:
        form = AddBookForm()
    return render(request, 'books/new.html', {'form': form})


@login_required
def download_book(request, book):
    file_path = os.path.join(settings.MEDIA_ROOT, book)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            # download = Download.objects.create(user=request.user)
            return response

    raise Http404


def search(request):
    q = request.GET.get('q', '')
    books = Book.books.filter(name__icontains=q)

    context = {
        'books': books,
        'categories': Gender.categories.all(),
        'authors': Author.authors.all(),
        'nofound': count_query(books),
    }
    return render(request, 'books/index.html', context)


def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    return render(request, 'books/detail.html',
                  {'book': book, 'comments': Comment.comments.filter(book_id__exact=book_id)})


@login_required
def recommend_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.recommended = book.recommended + 1
    book.save()
    return HttpResponse("Tu has recomendado este libro %s." % book_id)


def category(request, category):
    books = Book.books.filter(gender__name__icontains=category)

    context = {
        'books': books,
        'categories': Gender.categories.all(),
        'authors': Author.authors.all(),
        'no_book_category': count_query(books)
    }
    return render(request, 'books/index.html', context)


def author(request, author):
    books = Book.books.filter(author__name__icontains=author)

    context = {
        'books': books,
        'categories': Gender.categories.all(),
        'authors': Author.authors.all(),
        'no_book_author': count_query(books)
    }
    return render(request, 'books/index.html', context)


def count_query(query):
    """"
    Vertifica que la query devuelva mas de un registro
    """
    result = False
    if query.count() < 1:
        result = True
    return result

books/templates/books/detail.html
{% extends "layout_base.html" %}
{% block content %}
    <section class="content">
        <div class="container">
            <section class="content-header">
                <h1>


                </h1>

            </section>

            <div class="row">
                <div class="col-md-4">
                    <img src="{{ book.img_book.url }}" alt="">
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="row">
                            <div class="col-md-6">
                                <h2>Informacion Basica:</h2>
                            </div>
                            {% if user.is_authenticated %}
                                <div class="col-md-6">
                                    <a href="{% url 'books:download' book.file_book.name %}"
                                       style="float: right;margin-top: 15px"
                                       class="btn  btn-info">Descargar</a>
                                </div>
                            {% endif %}
                        </div>
                        <h5>Nombre : <b>{{ book.name }}</b></h5>
                        <h5>Autor : <b>{{ book.author }}</b></h5>
                        <h5>Generos :

                            <b>
                                {% for gender in book.gender.all %}
                                    <span class="badge bg-blue">{{ gender }}</span>
                                {% endfor %}
                            </b>
                        </h5>
                        <h5>Cantidad de paginas : <b>{{ book.amount_pages }}</b></h5>
                        <h5>Cantidad de capitulos : <b>{{ book.amount_chapter }}</b></h5>
                        <h5>Subido por : <b>{{ book.user }}</b></h5>
                        <!--<h4>Generos : <b>{{ book.gender }}</b></h4>-->

                        <h5>Descripcion :</h5>

                        <p>{{ book.description }}</p></p>
                    </div>


            </div>

        </div>
    </section>
{% endblock %}

books/templates/books/index.html
{% extends "layout_base.html" %}

<style>
        .widget-user-2 {
          overflow-x: scroll;
        }
      </style>

{% block content %}
    <section class="content">
        <div class="container">
            <!-- Content Header (Page header) -->

            <div class="col-md-3">
                <div class="row">
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header bg-blue">

                            <h3 class="widget-user-username">Categorias</h3>
                        </div>
                        <div class="box-footer no-padding">
                            <ul class="nav nav-stacked">

                                {% for category in categories %}
                                    <li><a href="{% url 'books:category' category.name %}">{{ category.name }} <span
                                            class="pull-right badge bg-blue"></span></a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header bg-blue">

                            <h3 class="widget-user-username">Autores</h3>
                        </div>
                        <div class="box-footer no-padding">
                            <ul class="nav nav-stacked">

                                {% for author in authors %}
                                    <li><a href="{% url 'books:author' author.name %}">{{ author.name }} <span
                                            class="pull-right badge bg-blue"></span></a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                </div>
                <!-- Widget: user widget style 1 -->


                <!-- /.widget-user -->
            </div>

            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        {% if nofound %}
                            <h2>Su busqueda no ahorro resultados...</h2>
                        {% endif %}

                        {% if no_book_category %}
                            <h2>En estos momentos no hay libro para esta categoria...</h2>
                        {% endif %}

                        {% if no_book_author %}
                            <h2>En estos momentos no hay libro para este autor...</h2>
                        {% endif %}
                    </div>

                    {% for book in books %}
                        <div class="col-md-3 col-sm-6">

                            <div class="product-grid7">
                                <div class="product-image7">
                                    <a href="#">
                                        <img class="pic-1"
                                             src="{{ book.img_book.url }}">
                                    </a>
                                    <a href="{% url 'books:detail' book.id %}" class="select-options"><i
                                            class="fa fa-arrow-right"></i>Ver</a>
                                </div>
                                <div class="product-content">
                                    <h3 class="title">{{ book.name }}</h3>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>


                <div class="row">
                    <div class="col-md-6">
                        {% if books.has_previous %}

                            <a class="btn btn-default" href="?page={{ books.previous_page_number }}" tabindex="-1">Anterior</a>

                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        {% if books.has_next %}
                            <a class="btn btn-default" style="float: right" href="?page={{ books.next_page_number }}"
                               tabindex="-1">Proximo</a>
                        {% endif %}

                    </div>
                </div>


            </div>


        </div>


    </section>



{% endblock %}

books/templates/books/login_error.html
<h1>Error login</h1>
<p>Debe iniciar sesion para usar esta accion</p>

books/templates/books/new.html
{% extends "layout_base.html" %}



{% block content %}
    <div class="container">
        <section class="content-header">
            <h1>
                Agregar libro

            </h1>

        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Nombre</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="author">Autor</label>

                                    {{ form.author }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Cantidad de paginas</label>
                                    {{ form.amount_pages }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Cantidad de capitulos</label>
                                    {{ form.amount_chapter }}
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="exampleInputPassword1">Generos</label>
                            {{ form.gender }}
                        </div>


                        <div class="col-md-4">

                        </div>

                </div>
                <div class="col-md-4">

                    <div class="form-group">
                        <label for="exampleInputFile">Sinopsis</label>
                        {{ form.description }}
                    </div>


                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="exampleInputFile">Foto Portada</label>
                                {{ form.img_book }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="exampleInputFile">Libro</label>
                                {{ form.file_book }}
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-4">

                    <input type="submit" value="Guardar Libro" name="submit" class="btn btn-info"
                           style="float: right;margin-top: 25px">
                       </form>

                </div>
            </div>



        </section>
    </div>
    <br>

{% endblock %}